//! `pxm.lock` — the resolved, content-hashed set of prompts, so a teammate
//! runs byte-identical prompts. The hash is a real SHA-256 of prompt.md,
//! which makes "byte-identical" a true statement rather than a slogan.

use crate::{registry, resolve};
use anyhow::Result;
use serde::Deserialize;
use sha2::{Digest, Sha256};

#[derive(Debug, Deserialize)]
pub struct Lock {
    pub root: String,
    #[serde(default)]
    pub prompt: Vec<LockEntry>,
}

#[derive(Debug, Deserialize)]
pub struct LockEntry {
    pub name: String,
    pub version: String,
    pub sha256: String,
}

pub fn hash_prompt(prompt: &str) -> String {
    let mut h = Sha256::new();
    h.update(prompt.as_bytes());
    h.finalize().iter().map(|b| format!("{b:02x}")).collect()
}

/// Render the lockfile text for a resolved set.
pub fn build(root: &str, resolved: &resolve::Resolved) -> Result<String> {
    let mut s = String::new();
    s.push_str("# pxm.lock — generated by pxm. Do not edit by hand.\n");
    s.push_str("version = 1\n");
    s.push_str(&format!("root = \"{root}\"\n\n"));
    for name in &resolved.order {
        let pkg = registry::load(name)?;
        s.push_str("[[prompt]]\n");
        s.push_str(&format!("name = \"{}\"\n", pkg.manifest.name));
        s.push_str(&format!("version = \"{}\"\n", pkg.manifest.version));
        s.push_str(&format!("sha256 = \"{}\"\n\n", hash_prompt(&pkg.prompt)));
    }
    Ok(s)
}
